sudo: false

language: node_js

node_js:
  - "8"
  - "10"

notifications:
  disabled: true

env:
  - TEST_DIR=client
  - TEST_DIR=server

install:
  - npm install -g codecov
  - npm install --prefix client
  - npm install --prefix server

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

script:
  - cd $TEST_DIR
  - npm test
  - codecov
